// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mesos/v1/allocator/allocator.proto

package org.apache.mesos.v1.allocator;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InverseOfferStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;
    /**
     * <code>required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;</code>
     */
    org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status getStatus();

    // required .mesos.v1.FrameworkID framework_id = 2;
    /**
     * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
     */
    boolean hasFrameworkId();
    /**
     * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
     */
    org.apache.mesos.v1.Protos.FrameworkID getFrameworkId();
    /**
     * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
     */
    org.apache.mesos.v1.Protos.FrameworkIDOrBuilder getFrameworkIdOrBuilder();

    // required .mesos.v1.TimeInfo timestamp = 3;
    /**
     * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
     *
     * <pre>
     * Time, since the epoch, when this status was last updated.
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
     *
     * <pre>
     * Time, since the epoch, when this status was last updated.
     * </pre>
     */
    org.apache.mesos.v1.Protos.TimeInfo getTimestamp();
    /**
     * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
     *
     * <pre>
     * Time, since the epoch, when this status was last updated.
     * </pre>
     */
    org.apache.mesos.v1.Protos.TimeInfoOrBuilder getTimestampOrBuilder();
  }
  /**
   * Protobuf type {@code mesos.v1.allocator.InverseOfferStatus}
   *
   * <pre>
   **
   * Describes the status of an inverse offer.
   *
   * This is a protobuf so as to be able to share the status to inverse offers
   * through endpoints such as the maintenance status endpoint.
   * </pre>
   */
  public static final class InverseOfferStatus extends
      com.google.protobuf.GeneratedMessage
      implements InverseOfferStatusOrBuilder {
    // Use InverseOfferStatus.newBuilder() to construct.
    private InverseOfferStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InverseOfferStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InverseOfferStatus defaultInstance;
    public static InverseOfferStatus getDefaultInstance() {
      return defaultInstance;
    }

    public InverseOfferStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InverseOfferStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status value = org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = value;
              }
              break;
            }
            case 18: {
              org.apache.mesos.v1.Protos.FrameworkID.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = frameworkId_.toBuilder();
              }
              frameworkId_ = input.readMessage(org.apache.mesos.v1.Protos.FrameworkID.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(frameworkId_);
                frameworkId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              org.apache.mesos.v1.Protos.TimeInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(org.apache.mesos.v1.Protos.TimeInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.mesos.v1.allocator.Protos.internal_static_mesos_v1_allocator_InverseOfferStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.mesos.v1.allocator.Protos.internal_static_mesos_v1_allocator_InverseOfferStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.class, org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<InverseOfferStatus> PARSER =
        new com.google.protobuf.AbstractParser<InverseOfferStatus>() {
      public InverseOfferStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InverseOfferStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InverseOfferStatus> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code mesos.v1.allocator.InverseOfferStatus.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 1;</code>
       *
       * <pre>
       * We have not received a response yet. This is the default state before
       * receiving a response.
       * </pre>
       */
      UNKNOWN(0, 1),
      /**
       * <code>ACCEPT = 2;</code>
       *
       * <pre>
       * The framework is ok with the inverse offer. This means it will not
       * violate any SLAs and will attempt to evacuate any tasks running on the
       * agent. If the tasks are not evacuated by the framework, the operator can
       * manually shut down the slave knowing that the framework will not have
       * violated its SLAs.
       * </pre>
       */
      ACCEPT(1, 2),
      /**
       * <code>DECLINE = 3;</code>
       *
       * <pre>
       * The framework wants to block the maintenance operation from happening. An
       * example would be that it cannot meet its SLA by losing resources.
       * </pre>
       */
      DECLINE(2, 3),
      ;

      /**
       * <code>UNKNOWN = 1;</code>
       *
       * <pre>
       * We have not received a response yet. This is the default state before
       * receiving a response.
       * </pre>
       */
      public static final int UNKNOWN_VALUE = 1;
      /**
       * <code>ACCEPT = 2;</code>
       *
       * <pre>
       * The framework is ok with the inverse offer. This means it will not
       * violate any SLAs and will attempt to evacuate any tasks running on the
       * agent. If the tasks are not evacuated by the framework, the operator can
       * manually shut down the slave knowing that the framework will not have
       * violated its SLAs.
       * </pre>
       */
      public static final int ACCEPT_VALUE = 2;
      /**
       * <code>DECLINE = 3;</code>
       *
       * <pre>
       * The framework wants to block the maintenance operation from happening. An
       * example would be that it cannot meet its SLA by losing resources.
       * </pre>
       */
      public static final int DECLINE_VALUE = 3;


      public final int getNumber() { return value; }

      public static Status valueOf(int value) {
        switch (value) {
          case 1: return UNKNOWN;
          case 2: return ACCEPT;
          case 3: return DECLINE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Status(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mesos.v1.allocator.InverseOfferStatus.Status)
    }

    private int bitField0_;
    // required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status status_;
    /**
     * <code>required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;</code>
     */
    public org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status getStatus() {
      return status_;
    }

    // required .mesos.v1.FrameworkID framework_id = 2;
    public static final int FRAMEWORK_ID_FIELD_NUMBER = 2;
    private org.apache.mesos.v1.Protos.FrameworkID frameworkId_;
    /**
     * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
     */
    public boolean hasFrameworkId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
     */
    public org.apache.mesos.v1.Protos.FrameworkID getFrameworkId() {
      return frameworkId_;
    }
    /**
     * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
     */
    public org.apache.mesos.v1.Protos.FrameworkIDOrBuilder getFrameworkIdOrBuilder() {
      return frameworkId_;
    }

    // required .mesos.v1.TimeInfo timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private org.apache.mesos.v1.Protos.TimeInfo timestamp_;
    /**
     * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
     *
     * <pre>
     * Time, since the epoch, when this status was last updated.
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
     *
     * <pre>
     * Time, since the epoch, when this status was last updated.
     * </pre>
     */
    public org.apache.mesos.v1.Protos.TimeInfo getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
     *
     * <pre>
     * Time, since the epoch, when this status was last updated.
     * </pre>
     */
    public org.apache.mesos.v1.Protos.TimeInfoOrBuilder getTimestampOrBuilder() {
      return timestamp_;
    }

    private void initFields() {
      status_ = org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status.UNKNOWN;
      frameworkId_ = org.apache.mesos.v1.Protos.FrameworkID.getDefaultInstance();
      timestamp_ = org.apache.mesos.v1.Protos.TimeInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrameworkId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFrameworkId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTimestamp().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, status_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, frameworkId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, frameworkId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.mesos.v1.allocator.Protos.InverseOfferStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mesos.v1.allocator.InverseOfferStatus}
     *
     * <pre>
     **
     * Describes the status of an inverse offer.
     *
     * This is a protobuf so as to be able to share the status to inverse offers
     * through endpoints such as the maintenance status endpoint.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.mesos.v1.allocator.Protos.InverseOfferStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.mesos.v1.allocator.Protos.internal_static_mesos_v1_allocator_InverseOfferStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.mesos.v1.allocator.Protos.internal_static_mesos_v1_allocator_InverseOfferStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.class, org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Builder.class);
      }

      // Construct using org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFrameworkIdFieldBuilder();
          getTimestampFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (frameworkIdBuilder_ == null) {
          frameworkId_ = org.apache.mesos.v1.Protos.FrameworkID.getDefaultInstance();
        } else {
          frameworkIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (timestampBuilder_ == null) {
          timestamp_ = org.apache.mesos.v1.Protos.TimeInfo.getDefaultInstance();
        } else {
          timestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.mesos.v1.allocator.Protos.internal_static_mesos_v1_allocator_InverseOfferStatus_descriptor;
      }

      public org.apache.mesos.v1.allocator.Protos.InverseOfferStatus getDefaultInstanceForType() {
        return org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.getDefaultInstance();
      }

      public org.apache.mesos.v1.allocator.Protos.InverseOfferStatus build() {
        org.apache.mesos.v1.allocator.Protos.InverseOfferStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.mesos.v1.allocator.Protos.InverseOfferStatus buildPartial() {
        org.apache.mesos.v1.allocator.Protos.InverseOfferStatus result = new org.apache.mesos.v1.allocator.Protos.InverseOfferStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (frameworkIdBuilder_ == null) {
          result.frameworkId_ = frameworkId_;
        } else {
          result.frameworkId_ = frameworkIdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.mesos.v1.allocator.Protos.InverseOfferStatus) {
          return mergeFrom((org.apache.mesos.v1.allocator.Protos.InverseOfferStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.mesos.v1.allocator.Protos.InverseOfferStatus other) {
        if (other == org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasFrameworkId()) {
          mergeFrameworkId(other.getFrameworkId());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasFrameworkId()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!getFrameworkId().isInitialized()) {
          
          return false;
        }
        if (!getTimestamp().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.mesos.v1.allocator.Protos.InverseOfferStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.mesos.v1.allocator.Protos.InverseOfferStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;
      private org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status status_ = org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status.UNKNOWN;
      /**
       * <code>required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;</code>
       */
      public org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status getStatus() {
        return status_;
      }
      /**
       * <code>required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;</code>
       */
      public Builder setStatus(org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .mesos.v1.allocator.InverseOfferStatus.Status status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = org.apache.mesos.v1.allocator.Protos.InverseOfferStatus.Status.UNKNOWN;
        onChanged();
        return this;
      }

      // required .mesos.v1.FrameworkID framework_id = 2;
      private org.apache.mesos.v1.Protos.FrameworkID frameworkId_ = org.apache.mesos.v1.Protos.FrameworkID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.mesos.v1.Protos.FrameworkID, org.apache.mesos.v1.Protos.FrameworkID.Builder, org.apache.mesos.v1.Protos.FrameworkIDOrBuilder> frameworkIdBuilder_;
      /**
       * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
       */
      public boolean hasFrameworkId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
       */
      public org.apache.mesos.v1.Protos.FrameworkID getFrameworkId() {
        if (frameworkIdBuilder_ == null) {
          return frameworkId_;
        } else {
          return frameworkIdBuilder_.getMessage();
        }
      }
      /**
       * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
       */
      public Builder setFrameworkId(org.apache.mesos.v1.Protos.FrameworkID value) {
        if (frameworkIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          frameworkId_ = value;
          onChanged();
        } else {
          frameworkIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
       */
      public Builder setFrameworkId(
          org.apache.mesos.v1.Protos.FrameworkID.Builder builderForValue) {
        if (frameworkIdBuilder_ == null) {
          frameworkId_ = builderForValue.build();
          onChanged();
        } else {
          frameworkIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
       */
      public Builder mergeFrameworkId(org.apache.mesos.v1.Protos.FrameworkID value) {
        if (frameworkIdBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              frameworkId_ != org.apache.mesos.v1.Protos.FrameworkID.getDefaultInstance()) {
            frameworkId_ =
              org.apache.mesos.v1.Protos.FrameworkID.newBuilder(frameworkId_).mergeFrom(value).buildPartial();
          } else {
            frameworkId_ = value;
          }
          onChanged();
        } else {
          frameworkIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
       */
      public Builder clearFrameworkId() {
        if (frameworkIdBuilder_ == null) {
          frameworkId_ = org.apache.mesos.v1.Protos.FrameworkID.getDefaultInstance();
          onChanged();
        } else {
          frameworkIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
       */
      public org.apache.mesos.v1.Protos.FrameworkID.Builder getFrameworkIdBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFrameworkIdFieldBuilder().getBuilder();
      }
      /**
       * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
       */
      public org.apache.mesos.v1.Protos.FrameworkIDOrBuilder getFrameworkIdOrBuilder() {
        if (frameworkIdBuilder_ != null) {
          return frameworkIdBuilder_.getMessageOrBuilder();
        } else {
          return frameworkId_;
        }
      }
      /**
       * <code>required .mesos.v1.FrameworkID framework_id = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.mesos.v1.Protos.FrameworkID, org.apache.mesos.v1.Protos.FrameworkID.Builder, org.apache.mesos.v1.Protos.FrameworkIDOrBuilder> 
          getFrameworkIdFieldBuilder() {
        if (frameworkIdBuilder_ == null) {
          frameworkIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.apache.mesos.v1.Protos.FrameworkID, org.apache.mesos.v1.Protos.FrameworkID.Builder, org.apache.mesos.v1.Protos.FrameworkIDOrBuilder>(
                  frameworkId_,
                  getParentForChildren(),
                  isClean());
          frameworkId_ = null;
        }
        return frameworkIdBuilder_;
      }

      // required .mesos.v1.TimeInfo timestamp = 3;
      private org.apache.mesos.v1.Protos.TimeInfo timestamp_ = org.apache.mesos.v1.Protos.TimeInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.mesos.v1.Protos.TimeInfo, org.apache.mesos.v1.Protos.TimeInfo.Builder, org.apache.mesos.v1.Protos.TimeInfoOrBuilder> timestampBuilder_;
      /**
       * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
       *
       * <pre>
       * Time, since the epoch, when this status was last updated.
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
       *
       * <pre>
       * Time, since the epoch, when this status was last updated.
       * </pre>
       */
      public org.apache.mesos.v1.Protos.TimeInfo getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
       *
       * <pre>
       * Time, since the epoch, when this status was last updated.
       * </pre>
       */
      public Builder setTimestamp(org.apache.mesos.v1.Protos.TimeInfo value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
       *
       * <pre>
       * Time, since the epoch, when this status was last updated.
       * </pre>
       */
      public Builder setTimestamp(
          org.apache.mesos.v1.Protos.TimeInfo.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
       *
       * <pre>
       * Time, since the epoch, when this status was last updated.
       * </pre>
       */
      public Builder mergeTimestamp(org.apache.mesos.v1.Protos.TimeInfo value) {
        if (timestampBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              timestamp_ != org.apache.mesos.v1.Protos.TimeInfo.getDefaultInstance()) {
            timestamp_ =
              org.apache.mesos.v1.Protos.TimeInfo.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
       *
       * <pre>
       * Time, since the epoch, when this status was last updated.
       * </pre>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = org.apache.mesos.v1.Protos.TimeInfo.getDefaultInstance();
          onChanged();
        } else {
          timestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
       *
       * <pre>
       * Time, since the epoch, when this status was last updated.
       * </pre>
       */
      public org.apache.mesos.v1.Protos.TimeInfo.Builder getTimestampBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
       *
       * <pre>
       * Time, since the epoch, when this status was last updated.
       * </pre>
       */
      public org.apache.mesos.v1.Protos.TimeInfoOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_;
        }
      }
      /**
       * <code>required .mesos.v1.TimeInfo timestamp = 3;</code>
       *
       * <pre>
       * Time, since the epoch, when this status was last updated.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.mesos.v1.Protos.TimeInfo, org.apache.mesos.v1.Protos.TimeInfo.Builder, org.apache.mesos.v1.Protos.TimeInfoOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.apache.mesos.v1.Protos.TimeInfo, org.apache.mesos.v1.Protos.TimeInfo.Builder, org.apache.mesos.v1.Protos.TimeInfoOrBuilder>(
                  timestamp_,
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:mesos.v1.allocator.InverseOfferStatus)
    }

    static {
      defaultInstance = new InverseOfferStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mesos.v1.allocator.InverseOfferStatus)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mesos_v1_allocator_InverseOfferStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mesos_v1_allocator_InverseOfferStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"mesos/v1/allocator/allocator.proto\022\022me" +
      "sos.v1.allocator\032\024mesos/v1/mesos.proto\"\327" +
      "\001\n\022InverseOfferStatus\022=\n\006status\030\001 \002(\0162-." +
      "mesos.v1.allocator.InverseOfferStatus.St" +
      "atus\022+\n\014framework_id\030\002 \002(\0132\025.mesos.v1.Fr" +
      "ameworkID\022%\n\ttimestamp\030\003 \002(\0132\022.mesos.v1." +
      "TimeInfo\".\n\006Status\022\013\n\007UNKNOWN\020\001\022\n\n\006ACCEP" +
      "T\020\002\022\013\n\007DECLINE\020\003B\'\n\035org.apache.mesos.v1." +
      "allocatorB\006Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mesos_v1_allocator_InverseOfferStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mesos_v1_allocator_InverseOfferStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mesos_v1_allocator_InverseOfferStatus_descriptor,
              new java.lang.String[] { "Status", "FrameworkId", "Timestamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.apache.mesos.v1.Protos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
